spring.application.name=LojaApi

spring.datasource.url=jdbc:mysql://localhost:3306/loja
spring.datasource.username=heitor
spring.datasource.password=senha123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true